import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import About from "./about";
import Contact from "./contact";
import Home from "./home";
import Navbar from "./navbar";

export default function Landing() {

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles.scrollContainer}>
          <div className={styles.home}>
            <section id="home">
              <Home />
            </section>
            {/* about section that the page focuses on when the link to about section is clicked on */}
            <div>
              <section className={styles.about} id="about">
                <About />
              </section>
            </div>
            {/* contact section that the page focuses on when the link to contact section is clicked on */}
            <section id="contact">
              <Contact />
            </section>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
